import { HorizontalBox, VerticalBox } from "std-widgets.slint";
import { Themes } from "../components/Themes.slint";

export component Tooltip inherits Rectangle {
    in property <string> text: "";
    in property <string> placement: "top";
    in property <bool> show: false;

    property <length> arrow-size: 6px;

    opacity: root.show ? 1 : 0;
    z: 999;

    width: content.width + 14px;
    height: content.height + 15px;

    background: Themes.current.tooltip-bg;
    border-radius: Themes.border-radius;
    drop-shadow-color: Themes.shadow-color;
    drop-shadow-blur: Themes.shadow-size;

    content := Text {
        x: 8px;
        y: 8px;
        text: root.text;
        font-size: 12px;
        color: Themes.current.primary-text;
        font-family: Themes.font-family-display;
    }

    arrow-top := Path {
        visible: placement == "top";
        fill: Themes.current.tooltip-bg;

        width: 12px;
        height: 6px;

        x: root.width / 2 - 6px;
        y: -6px;

        commands: "M 0 6 L 6 0 L 12 6 Z";
    }

    arrow-bottom := Path {
        visible: placement == "bottom";
        fill: Themes.current.tooltip-bg;

        width: 12px;
        height: 6px;

        x: root.width / 2 - 6px;
        y: root.height;

        commands: "M 0 0 L 6 6 L 12 0 Z";
    }

    arrow-left := Path {
        visible: placement == "left";
        fill: Themes.current.tooltip-bg;

        width: 6px;
        height: 12px;

        x: -6px;
        y: root.height / 2 - 6px;

        commands: "M 6 0 L 0 6 L 6 12 Z";
    }

    arrow-right := Path {
        visible: placement == "right";
        fill: Themes.current.tooltip-bg;

        width: 6px;
        height: 12px;

        x: root.width;
        y: root.height / 2 - 6px;

        commands: "M 0 0 L 6 6 L 0 12 Z";
    }

    animate opacity {
        duration: 150ms;
    }
}

